// typer
typer('.typewriter')
  .line('Hello, World!')
  // .continue(' 👋', 1) TODO: not as trash
  .pause(2000)
  .back('all')
  .pause(100)
  .line('I\'m Fal')
  .pause(100)
  .back(2)
  .pause(100)
  .continue('xllenCode!')
  .pause(2000)
  .back('all')
  .pause(100)
  .line('I am a Roblox Developer.')
  .pause(2000)
  .back(17)
  .pause(250)
  .continue('Lua Programmer.')
  .pause(2000)
  .back(15)
  .pause(250)
  .continue('Front-End Web Developer.')
  .pause(2000)
  .back(24)
  .pause(250)
  .continue('Security Researcher.')
  .pause(2000)
  .back(22)
  .pause(250)
  .continue('an Open-Source Contributor.')
  .pause(2000)
  .back('all')
  .pause(100)
  .line('Check out my projects below!')
  .pause(2000)
  .back('all')
  .pause(100)
  .line('My contact information is also there.')
  .pause(2000)
  .back('all')
  .pause(100)
  .line('Thanks for checking out my website!')
  .pause(250)
  .back(8)
  .pause(100)
  .continue('portfolio!')
  .pause(10000)
  .back('all',20)
  .repeat(Infinity)

  // /typer